### ISSUE TITLE
Feedback from Ross Hart

### ISSUE THREAD

**Issue by willettk** [willettk/gzhubble#110]
- [x] After reading through the method section, I seem to be able to follow
  it, which is great. The only secion I would expand out a little bit is
  section 4.1- I'd try to make it realy explicit exactly what is going on
  at each stage, ie. how is the redshift data binned in SDSS --> how is it
  then binned in FERENGI... I know this might seem a bit long, but I think
  it would make it much easier to follow.
- [x] In figure 6, some of the plots look like bad fits to the data-
  however, on inspection, the worst fits are with the lowest f0 values.
  I'd order the plots by f0 going from low -> high, so that it is clear
  that all of the plots with 'bad' fits are together, and it is clear that
  they are all in the low f0 part of the plot.
- [x] In section 6.1, I think people may think that there may be a
  classification bias in the fraction of barred galaxies. However, I think
  I found that bar fractions don't change much with redshift in the low-z
  SDSS data, so maybe put in a sentence saying this so that people don't
  'question' this result.
- [x] Just a general point- you don't really include any images of
  'reccovered' galaxies until the appendix- for example, you could show
  some of the barred vs. unbarred galaxies earlier on. In morphology
  papers, I really like, say, making a cut in the data, then puting a
  figure explaining this- if all of the morphologies are what we describe
  (which they almost always are in GZ usually), follow it up with a subset
  of images as 'proof'. I just think that makes the GZ morphologies look
  really good!

**Comment by karenlmasters** [comment]
For Section 6.1 on bars I think we can cite more of the results Tom presented in his thesis. Melanie has the latest version now. What we found was that once features are identified you will always see a bar - the discs fade first. Tom made a plot of f_bar(z) in the FERENGI sample and showed that it was completely flat - no evolution with redshift. I think that's important to mention. It's not published, but it's allowed to refer to a PhD thesis.

**Comment by karenlmasters** [comment]
So basically I disagree that you'd want a cut on fbar that evolved with redshift, and I don't think we should even mention that as I think it will confuse people.

**Comment by vrooje** [comment]
That plot in Tom's thesis was really good and I don't think it's anywhere else; eventually the thesis will be on ADS but I'm not sure what the procedure is for citing it before then?

Anyway, I agree.

**Comment by willettk** [comment]
Added some text in #132 - please chime in if you think we should add more. It's a short reference right now, so we may want more detail.

**Comment by willettk** [comment]
Closed with a couple different changes, but see #132, #145. Thanks, Ross.
