### ISSUE TITLE
Add RA and Dec to main downloadable data table (e.g. Tables 5-11)

### ISSUE THREAD

**Issue by rjsmethurst** [willettk/gzhubble#125]
Table 5 shows something similar to what you sent me via dropbox the other day and for some reason it doesn't contain RA and Dec? I had to cross match myself to the meta_catalog - it would be good to get RA and Dec (at least) provided in the main data tables - it's what people will be using to cross match with their catalogues after all (rather than the IDs). If they want further information (e.g. redshift) they can then cross match with the meta catalog.

**Comment by Mel23** [comment]
Closed in Dropbox - thanks for the suggestion! I agree having those in both catalogs is useful.
