### ISSUE TITLE
general feedback from Becky

### ISSUE THREAD

**Issue by rjsmethurst** [willettk/gzhubble#126]
Three very small things:
- [x] Figure 9 is mentioned before Figure 8 so those should probably have their numbering switched
- [ ] In section 4.3 at the end of the paragraph on page 11 could we refer the reader to the top right panel of Figure 9 so they know where to look for high z and low mu?
- [x] In Section 6 would you mind adding a reference to Smethurst et al. (2015) and talk about using the GZ classifications as weights rather than using a threshold?

**Comment by willettk** [comment]
Good suggestions, @rjsmethurst. 

I can't seem to find the point where you suggested referencing Figure 9 in the current version of the draft (it's under rapid reconstruction). Can you point me to a line number (or give a couple sentences of context where you think this should go)?

**Comment by rjsmethurst** [comment]
This is the paragraph I was talking about in the second point - it's now on p.12 of the draft:
"Figure 9 shows that the relationship between f_features,z and f_features,z=0.3 is not always single valued; hence, it is not appropriate to correct galaxies that lie in certain regions of surface brightness/redshift/f_features space. These regions tend to have low f_features values at high redshift, but a wide range of values at z = 0.3. These regions contain two morphological types of galaxies: the first set are genuine ellipticals, which have low values of f_features at both high and low redshift. The second group are disks whose features become indistinct at high redshift; hence their f_features value at z = 0.3 may be quite high, while the value observed at high redshift is very low. This effect is strongest at high z and low μ, where features become nearly impossible to discern in the images."

I suggest adding a bracket at the end of the last sentence such as: "(see top right panel of Figure 9a)" - so that readers can see how that is reflected in those plots. Up to you though!
