### ISSUE TITLE
Acronyms in Abstract

### ISSUE THREAD

**Issue by karenlmasters** [willettk/gzhubble#127]
Just a note that the journal may ask for all acronyms to be defined in the abstract. This will be messy with GEMS, AEGIS, COSMOS and GOODS, so the solution might be to not name then there, but just say that all public HST surveys are used.

**Comment by willettk** [comment]
gaaaaaaaah. You're very right, @karenlmasters. I just wish they wouldn't demand that. 

I think I'm going to leave it for now because the abstract is more readable, and cross my fingers that the editor won't ask us. Will open back up later if necessary.
