### ISSUE TITLE
Section 6.1

### ISSUE THREAD

**Issue by karenlmasters** [willettk/gzhubble#128]
- [x] In the section describing Cheung et al. (2015) I think we should point out that that work compared the bar fraction of AGN with galaxies without AGN at the same redshift. Because of that technique the impact of redshift bias was minimal, as the comparison and test sample were both at the same redshift. Edmond might like to correct me if I'm remembering that incorrectly. 
- [x] Also the section on clumps starts with why clumps are interesting, but the section on bars does not. We should be consistent - either mention a few words about why bars are interesting, or remove the science from the clump section. I'm in favour of the former.

**Comment by karenlmasters** [comment]
Also the section on clumps starts with why clumps are interesting, but the section on bars does not. We should be consistent - either mention a few words about why bars are interesting, or remove the science from the clump section. I'm in favour of the former.

**Comment by willettk** [comment]
Can I ask you for a couple sentences on why bars are interesting, @karenlmasters? I'll put it into the manuscript if you do - I agree that we should motivate bar science rather than drop clumpy science.

**Comment by karenlmasters** [comment]
Hows this? All of these references in Tom's bar paper I think (except Simmons et al. which was obviously published after that): 

"Bars in disc galaxies are a trace of the dynamic state of the disc of a galaxy (e.g. Combes 2009, Athanassoula 2012). Discs which have significant vertical motions typically do not form bars (with the exception of tidally trigger bars, Barnes & Hernquist 1991), but once a disc settles to a thin, dynamically cool state, the formation of bars proceeds quickly. Most theoretical predictions show that bars are long lasting in the absence of significant galaxy interactions (Athannassoula et al. 2005), so the fraction of bars in a population of disc galaxies provides a trace of the dynamical maturity of that population. For this reason tracking the fraction of bars in disc galaxies as a function of redshift has attracted significant interest since the first resolved images of high redshift galaxies were obtained (e.g. Abraham et al. 1999, Elmegreen, Elmegreen & Hirst 2004, Jogee et al. 2004, Sheth et al. 2008, Melvin et al. 2014, Simmons et al. 2015). "

**Comment by willettk** [comment]
That was excellent. Thanks, Karen.
