### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by karenlmasters** [willettk/gzhubble#129]
I absolutely love the current introduction. I think it's a fantastic overview and really well written. :) 

Two minor things: 
- [x] Can we cite Lahav et al. (1993) in the section on Expert morphology. While the paper is framed around machine learning/automated classification, I think it's relevent  to this section because it includes a direct comparison of 8 of the big expert classifiers alive at the time. :) Add it here: "but suffer from issues such as lack of scaling to large sur- veys and potential issues with replicability and calibration (e.g. see Lahav et al. 1993 for a discussion on the extent to which 8 expert classifiers agree with each other)."
- [x] State that main difference with GZ: CANDELS is NIR imaging at high redshift.

**Comment by willettk** [comment]
That's very flattering - thanks, @karenlmasters. Significant help from Brooke and Steven on that, which vastly helps mask the fact I wrote the first draft in an hour. 

I didn't find a reference for Lahav et al. (1993) - I'd guess you meant [Lahav et al. (1995)](https://ui.adsabs.harvard.edu/#abs/1995Sci...267..859L/abstract)?
