### ISSUE TITLE
Figure 11 and associated discussion

### ISSUE THREAD

**Issue by claudiascarlata** [willettk/gzhubble#134]
I think this figure is misleading and the associated discussion is not very informative.
You do point out that the distribution of galaxy types depends on redshifts and magnitudes as well as how you define a classification in GZ. So what point are you trying to make with this figure? 

Why instead don't we make a comparison of the distribution for COSMOS and everything else? COSMOS is the only field where ground based data have been used -- so it would be usefuls to see if the raw distributions of morphological types change due to the different data used.

**Comment by willettk** [comment]
Agreed, but moving into #94.
