### ISSUE TITLE
Figure 8 : debiassing

### ISSUE THREAD

**Issue by claudiascarlata** [willettk/gzhubble#135]
My main issue with the paper is the debiassing. Specifically, the mismatch between the properties of the ferengi galaxies and the actual observed galaxies (Figure 8).
This implies that most of the parameter space covered by real galaxies is not sampled and therefore we cannot attempt a correction. Exaclty how many galaxies can we get reasonable classification for?

The small number of ferengi galaxies in each bin of z/mu is obviously another problem...
I am  not sure what can be done at this point, but I am afraid this may be a major point in the referee's comment.

**Comment by karenlmasters** [comment]
It's just the case that the local Universe has limited galaxies with such high surface brightness as are found in the high redshift. This is a limitation, but I think this sample is close to the best we can do. That said I would do it differently if starting now. There's an entire Chapter in Tom's thesis discussing what a sample should look like to do this ideally.

**Comment by willettk** [comment]
Very valid points, and something we've gradually realized over the last year. I think I should cite Tom's thesis specifically detailing that; I think the text here will try to balance between endorsing our approach as hopefully reliable, but not perfect, while acknowledging what we can do to make it better.

**Comment by bamford** [comment]
I don't understand this figure (which is Fig. 6 in the current version of the paper).

The y-axis label says mu_{max}.  Can you remind me what this is (I guess the SB at z=0.3)?  Is it correct to be comparing that with the _actual_ SB of the ACS sample galaxies?

The plot seems to indicate that the FERENGI galaxies cover higher surface brightnesses than the real galaxies.

**Comment by bamford** [comment]
Looking at the data table, I see mu_max_i is different for each simulated galaxy.  Where does it come from?  I'm still confused, as in 4.1 it calls the SB (mu_r) an 'intrinsic' property, but that is only the case if it is the SB at some fixed redshift.

**Comment by Mel23** [comment]
> > The plot seems to indicate that the FERENGI galaxies cover higher surface brightnesses than the real galaxies.

Yes, yes it does. Which is lame! But what we have to deal with. Like Karen said, Tom's thesis addresses how this selection could be improved. For now it's what we have to work with. 

> > Looking at the data table, I see mu_max_i is different for each simulated galaxy. Where does it come from? 

Mentioned in Section 4, they're measured for each image using SExtractor. The differences arise because of that, plus the different evolutions for the same galaxies. Once I figure out the proper way, we'll want to cite Tom's thesis.

**Comment by willettk** [comment]
Tom's thesis is now added as a reference; just use \cite{mel16}.
