### ISSUE TITLE
organization of the paper

### ISSUE THREAD

**Issue by claudiascarlata** [willettk/gzhubble#136]
I think in the main body of the paper we should present the morphology of the main legacy fields: GEMS, AEGIS, COSMOS, GOODS(NS).
All the other datasets add only confusion (for example, in Figure 11 what do you include?) and are not being really used.
As we discussed yesterday, they have a place in the appendix. I think the fact that historically they were classified within GZH doesn't mean they belong to this paper.

**Comment by willettk** [comment]
Closed with 3a4191f6a5d33fb435e8bdb4853a89276f0a14ce.
