### ISSUE TITLE
Are 3 sig fig warranted on the comsological parameters? 

### ISSUE THREAD

**Issue by karenlmasters** [willettk/gzhubble#162]
We quote: (Ωm, ΩΛ, h) = (0.282, 0.718, 0.697) for cosmology parameters. This seems like too many sig fig to me....

**Comment by willettk** [comment]
It's close to the uncertainties in Table 4 of Hinshaw et al. (2013), depending on which parameter we're looking at. They formally quote:

Ωb = 0.04628 ± 0.00093
Ωc = 0.2402 + 0.0088−0.0087
ΩΛ = 0.7135+0.0095
H0 = 69.32 ± 0.80

So while I actually do need to adjust these (thanks, Karen - I think I used WMAP9 only vs. WMAP9 + all external data), we should be at the same level of precision or less, although we don't quote the error bars along with it. I don't see the latter very commonly done these days, though, and 10^-3 shouldn't make any significant difference for the content of our paper.
