### ISSUE TITLE
tables 4, 6 & 10

### ISSUE THREAD

**Issue by lfortson** [willettk/gzhubble#165]
Table 4 is cutoff at the right margin.  This is also true of table 6 & 10.

**Comment by willettk** [comment]
True. Rotating doesn't make them look much better; I wanted to make all of the columns for `t01_*` visible, though, which makes it run over a bit. They'll correct that for the proofs, but I wanted to make it clear for a referee.

**Comment by willettk** [comment]
Closed with 3a4191f6a5d33fb435e8bdb4853a89276f0a14ce.
