### ISSUE TITLE
Final versions of full tables for data.galaxyzoo.org

### ISSUE THREAD

**Issue by willettk** [willettk/gzhubble#174]
Finalizing the data that will go on data.galaxyzoo.org; first for the referee/editor (if desired), and later for the general public. FITS tables for all. 
- [x] final debiased morphology tables (including simulated_agn) all in the same folder, consistently named
- [x] add MAG_BEST_HI to morphology tables
- [x] reorganize column order
- [x] add and rename GZ_MU_HI to meta tables
- [x] make metadata table for FERENGI
- [x] make classifications table for FERENGI
- [x] column descriptions file for FERENGI

Send to @willettk once done and we'll put them on data.galaxyzoo.org.

**Comment by Mel23** [comment]
@willettk: 

Tables should all be final versions now. In Dropbox we have:

in hubble_files/catalog_debiasing_files/new_sb_method:

1) catalog_5_27_2016_faded.fits
2) catalog_5_27_2016_fake_agn.fits
3) catalog_5_27_2016_ferengi.fits
4) catalog_5_27_2016_goods_shallow.fits
5) catalog_5_27_2016_hubble.fits
6) catalog_5_27_2016_recoloured.fits
7) catalog_5_27_2016_sdss_coadd.fits
8) catalog_5_27_2016_sdss_single.fits

In gzhubble/hubble_files/meta_catalogs we have:

1) meta_catalog_3_23_3016_goods_full.fits
2) meta_catalog_3_23_3016_goods_shallow.fits
3) meta_catalog_3_23_3016_hubble.fits
4) meta_catalog_3_23_3016_sdss_coadd.fits
5) meta_catalog_3_23_3016_sdss_single.fits
6) meta_catalog_ferengi.fits

I kept the old dates in the filenames for now; I assume you'll take out the dates when you upload them to data.galaxyzoo.org, but figured I'd keep them in in Dropbox in case we make new versions after the referee report. Let me know if you have questions.

**Comment by willettk** [comment]
Tables are on data.galaxyzoo.org. See https://github.com/zooniverse/data.galaxyzoo.org/pull/31.
