### ISSUE TITLE
Referee Report: MAJOR COMMENT I: Reorganization of Section 4

### ISSUE THREAD

**Issue by Mel23** [willettk/gzhubble#175]
> I spent an inordinate amount of time trying to piece together the analysis
> of Section 4 before discovering that important information was given later
> (in Section 4.2) rather than earlier (in Section 4.1).
> 
> I believe that Section 4.2 should come first: present the FERENGI sample, and
> discuss the scheme used to select those data that are to be analyzed to
> determine the debiasing correction. Then the details of the statistical model
> for debiasing (currently in Section 4.1) should come next.
> 
> Section 4.3 is fine where it is placed. (However, see minor comment 10 below,
> which actually is not quite as minor as the other comments.)

I personally completely agree with this comment, and shouldn't be too difficult to change. I'll revise this after we have settled on what changes, if any, we will implement to the zeta method.

**Comment by willettk** [comment]
Closed with #194 and 6ce701cecebff09d5488540a5823130ef8069eea.
