### ISSUE TITLE
debias as a function of redshift

### ISSUE THREAD

**Issue by lfortson** [willettk/gzhubble#187]
Based on further conversations between Claudia, Chris and Lucy, on a plot that Mel generated showing the f_features distribution for four different redshift bands (below), we think it is important that the paper more clearly points out that this will curtail the ability for any user to do population studies with the debiased galaxies within a redshift band as well as any evolutionary studies across redshift bands.  Currently, there is a description of the issue in section 4.2 but we think this limitation needs to be clearly stated in at minimum the discussion/conclusions.

![pfeaturesredshift](https://cloud.githubusercontent.com/assets/1714816/17184988/f76600da-5426-11e6-89fb-5cd9c3117911.png)

**Comment by karenlmasters** [comment]
I think this is a good point, however we should point out that as long as the users make use of thresholds which lump all things with uncorrectable f_features at all redshifts together (ie. ffeatures<0.7 if want to use up to z~1) this can still be used to do evolutionary studies. 

The reason these look so different is the fact that the threshold for uncorrectable galaxies moves ot higher ffeatures with redshift.

**Comment by Mel23** [comment]
This was my thought as well - any study should make use of both the correctable and uncorrectable samples, with the grain of salt that the uncorrectable f_features _are_ upper limits estimates. I think the concern from Lucy was that the casual reader might jump to the conclusion that they should only be using the correctable sample in studies, unless it is made very obvious not to just do that.
