### ISSUE TITLE
Final paragraph from referee. 

### ISSUE THREAD

**Issue by karenlmasters** [willettk/gzhubble#188]
Just wanted to comment how much I enjoyed this final paragraph: 

"Given the comments above, one could surmise that I only really read Section 4.
But no: the authors are experts on Galaxy Zoo, galaxy morphology, and data
preparation, etc., and this shows throughout the rest of the text, which I
read and with which I have no issues (aside from minor comments 1 and 11
above). I look forward to their representation of the material in Section 4.
If the authors require clarification on anything I wrote above regarding
Section 4, I am presumably contactable via the MNRAS scientific editor."

**Comment by willettk** [comment]
Me too. :) Gives you hope for the whole single-referee peer review system
of astronomy, if we get more thoughtful reports like this.
