### ISSUE TITLE
New version of Figure 10 with new normalizaion

### ISSUE THREAD

**Issue by Mel23** [willettk/gzhubble#192]
A version of figure 10 to be made using the new normalization

**Comment by willettk** [comment]
Was this addressed with #195, @Mel23 ?

**Comment by Mel23** [comment]
Unless I couldn't find it, I only saw the old script uploaded, not a new figure (the script was still using the old normalization). I updated and ran the code with the new normalization and created an updated figure. Relevant pull request with both was just submitted for branch zeta_examples_figure.

**Comment by willettk** [comment]
Closed with #196.
