### ISSUE TITLE
Goods redshift sources

### ISSUE THREAD

**Issue by Mel23** [willettk/gzhubble#34]
Update Dropbox/hubble_files/goodsfull_t01_z_mu.fits to include a column of redshift sources. Please comment with algorithm used for selecting source.

**Comment by willettk** [comment]
We discovered:
- @willettk has a full set of spectroscopic and photometric redshifts combined from 3D-HST, MUSYC, and the ACS-GC. 
- For some reason, the redshifts attached to the full-depth metadata only included ACS-GC photometric redshifts, though. That's an error, so it's very good that it was caught. 
- @Mel23 has the full set of data and will apply the same redshift selection algorithm to make the correct metadata. 
- All files should be updated with these new values.

**Comment by Mel23** [comment]
Closed with 0db3415e6689c2c84b4d07eff81bc625a4a3a22c

**Comment by willettk** [comment]
Great!
