### ISSUE TITLE
Change "Griffith" to "ACS-GC" in the tables

### ISSUE THREAD

**Issue by willettk** [willettk/gzhubble#37]
While I know that is our shorthand, we should refer to it by the survey name, not the author (same as we do for the other tables). I've changed it in the text - @Mel23, can you do the same for the relevant columns in the data tables?

**Comment by Mel23** [comment]
Done! All metadata tables are now in Dropbox, there are 5: 

meta_catalog_3_23_2016_hubble.fits
-AEGIS, COSMOS, GEMS data
-contains all Griffith et al. metadata columns + image url + our Z_BEST, Z_BEST_TYPE, and Z_BEST SOURCE data

meta_catalog_3_23_2016_goods_shallow.fits
-GOODS shallow data
-contains all Griffith et al. metadata columns + image url + our Z_BEST, Z_BEST_TYPE, and Z_BEST SOURCE data

meta_catalog_3_23_2016_goods_full.fits
-GOODS full data
-contains some magnitudes and sizes, don't know the source though (@willettk is this information sufficient ?) 

meta_catalog_3_23_2016_sdss_single.fits
meta_catalog_3_23_2016_sdss_coadd.fits
-Stripe 82 data from the wiki table - gz_hst_info_sdss.fits
-source presumably sdss but should verify

**Comment by willettk** [comment]
Is it possible to merge the `_hubble` and `_goods_full` metadata tables?
The morphology annotations are merged in the paper already.

**Comment by Mel23** [comment]
Replying via email because mobile:

I could but it depends on which would be less confusing; yes they have the
same morphological data, but we don't have the same Metadata (hubble has
all the info Griffith offers; only a small subset of that is currently
known for the full depth sample. )

**Comment by willettk** [comment]
OK. Probably fine, at least for now.
