### ISSUE TITLE
User weighting

### ISSUE THREAD

**Issue by willettk** [willettk/gzhubble#40]
Is the distribution of user weighting similar to that in GZ1 and/or GZ2? I don't think we need a detailed analysis, but a sentence or two would be useful.

**Comment by bamford** [comment]
Here are the same(ish) plots from **GZ2**:
![user_consistency_gz2](https://cloud.githubusercontent.com/assets/219174/14563362/6df37bc4-0319-11e6-9e63-03b0975f6217.png)
and **GZ:HST**:
![user_consistency_gzhst](https://cloud.githubusercontent.com/assets/219174/14563396/a3bc5a6e-0319-11e6-804a-a76b9d2820b6.png)
I can't remember why the consistency scales are different, but the effect is the same: the user weighting is 1 for all except the worst (most inconsistent) 5% of users, then it smoothly drops to 0 for the worst 1%.

I think this measure of consistency is ok for down-weighting the worst contributors, but I think if we ever want to do a more general job of weighting it would be worth thinking the whole thing through again.

**Comment by willettk** [comment]
Excellent - that's the extent of what I needed for now. Thanks, @bamford!
