### ISSUE TITLE
Revise Decision Tree Figure so Task numbers match those in catalog

### ISSUE THREAD

**Issue by Mel23** [willettk/gzhubble#42]
Currently Figure 4 in the paper. The Task numbers are not the same as those in the gzh catalog column labels. 

Was Coleman the creator of this image, or does anyone else have the code?

**Comment by willettk** [comment]
@ckrawczyk made it; you might be able to change the labels if you made a
branch and played with
https://github.com/zooniverse/data.galaxyzoo.org/tree/master/public/gz_trees

**Comment by Mel23** [comment]
I've never worked in Java, is anyone else able to tackle this one?

**Comment by willettk** [comment]
Java != Javascript

**Comment by Mel23** [comment]
Okay, comment still stands - I'm not familiar with the filetype. Help!

**Comment by vrooje** [comment]
What do the labels need to be? Illustrator may come to the rescue here &
I'm sitting at this conference...

**Comment by Mel23** [comment]
I'll link a list shortly

**Comment by Mel23** [comment]
These are the columns numbered as they'll be in the final catalog. If this
is easy for you to execute Brooke, thank you! Otherwise I'm sure I can
figure it out, it just wouldn't be super quick.

t01_smooth_or_features
t02_edgeon
t03_bar
t04_spiral
t05_bulge_prominence
t06_odd
t07_rounded
t08_odd_feature
t09_bulge_shape
t10_arms_winding
t11_arms_number
t12_clumpy
t13_bright_clump
t14_bright_clump_central
t15_clumps_arrangement
t16_clumps_count
t17_clumps_symmetrical
t18_clumps_embedded

**Comment by vrooje** [comment]
[gzh_decision_tree.pdf](https://github.com/willettk/gzhubble/files/237391/gzh_decision_tree.pdf)

Like this?
(I'm not sure I trust the conference wifi to pull, branch, push, pull request)

**Comment by vrooje** [comment]
Also: are the response A# numbers single-indexed too? I haven't changed that...

**Comment by Mel23** [comment]
Ahh you are correct - sorry for not catching that before. The answer
numbers are changed slightly....

t01_smooth_or_features_a01_smooth_fraction
t01_smooth_or_features_a02_features_or_disk_fraction
t01_smooth_or_features_a03_star_or_artifact_fraction
t02_edgeon_a01_yes_fraction
t02_edgeon_a02_no_fraction
t03_bar_a01_bar_fraction
t03_bar_a02_no_bar_fraction
t04_spiral_a01_spiral_fraction
t04_spiral_a02_no_spiral_fraction
t05_bulge_prominence_a01_no_bulge_fraction
t05_bulge_prominence_a02_just_noticeable_fraction
t05_bulge_prominence_a03_obvious_fraction
t05_bulge_prominence_a04_dominant_fraction
t06_odd_a01_yes_fraction
t06_odd_a02_no_fraction
t07_rounded_a01_completely_round_fraction
t07_rounded_a02_in_between_fraction
t07_rounded_a03_cigar_shaped_fraction
t08_odd_feature_a01_ring_fraction
t08_odd_feature_a02_lens_or_arc_fraction
t08_odd_feature_a03_disturbed_fraction
t08_odd_feature_a04_irregular_fraction
t08_odd_feature_a05_other_fraction
t08_odd_feature_a06_merger_fraction
t08_odd_feature_a07_dust_lane_fraction
t09_bulge_shape_a01_rounded_fraction
t09_bulge_shape_a02_boxy_fraction
t09_bulge_shape_a03_no_bulge_fraction
t10_arms_winding_a01_tight_fraction
t10_arms_winding_a02_medium_fraction
t10_arms_winding_a03_loose_fraction
t11_arms_number_a01_1_fraction
t11_arms_number_a02_2_fraction
t11_arms_number_a03_3_fraction
t11_arms_number_a04_4_fraction
t11_arms_number_a05_more_than_4_fraction
t11_arms_number_a06_cant_tell_fraction
t12_clumpy_a01_yes_fraction
t12_clumpy_a02_no_fraction
t13_bright_clump_a01_yes_fraction
t13_bright_clump_a02_no_fraction
t14_bright_clump_central_a01_yes_fraction
t14_bright_clump_central_a02_no_fraction
t15_clumps_arrangement_a01_line_fraction
t15_clumps_arrangement_a02_chain_fraction
t15_clumps_arrangement_a03_cluster_fraction
t15_clumps_arrangement_a04_spiral_fraction
t16_clumps_count_a02_2_fraction
t16_clumps_count_a03_3_fraction
t16_clumps_count_a04_4_fraction
t16_clumps_count_a05_more_than_4_fraction
t16_clumps_count_a06_cant_tell_fraction
t16_clumps_count_a01_1_fraction
t17_clumps_symmetrical_a01_yes_fraction
t17_clumps_symmetrical_a02_no_fraction
t18_clumps_embedded_a01_yes_fraction
t18_clumps_embedded_a02_no_fraction

**Comment by willettk** [comment]
Does single-indexed mean zero-padded, or something different?

**Comment by vrooje** [comment]
single-indexed, i.e. start counting from 1. Sorry for shorthand.
[gzh_decision_tree.pdf](https://github.com/willettk/gzhubble/files/237476/gzh_decision_tree.pdf)

Better? Definitely double-check every single item :)

Also, I had to switch the order of clump arrangement answers in vrooje/gzcandels_datapaper#50 in the same way, so this may be a bug in the tree generation code.

**Comment by Mel23** [comment]
Double checked - only 1 error found! Task 13 - bright_clump_yes should be
a01, bright_clump_no should be a02

Also - is there an easy way to generate a cropped pdf for putting in the
paper? Or remove the date, page number, link, and 'redirecting' title from
the output?

**Comment by vrooje** [comment]
[gzh_decision_tree.pdf](https://github.com/willettk/gzhubble/files/237505/gzh_decision_tree.pdf)

Oh! Hah, I was so zoomed-in I didn't even see the header and footer. Should now be gone, and also cropped more closely. Answer order changed!

**Comment by Mel23** [comment]
You rock, thank you! I hope this kept you entertained at your conference.

**Comment by vrooje** [comment]
It always tickles me that I can edit a PDF or EPS directly like this :)

(it's actually a really good conference but this is just so much easier in Illustrator and I couldn't watch you go through learning Javascript if I could help...)

**Comment by CKrawczyk** [comment]
For future reference these values are here in the code: https://github.com/zooniverse/data.galaxyzoo.org/blob/master/public/gz_trees/config/gz3_tree.json

Changing the `name` or `question` value in the `nodes` list will do this.  The PDFs were made by using the browsers "print to PDF" feature (the navigation buttons don't show up in the print by default).  Changing the positions of the answers takes a bit more care to make sure the lines don't overlap, this can be done by editing the `group_x` and `group_y` values.

**Comment by willettk** [comment]
Closed with #43.
