### ISSUE TITLE
Lintott - suggested checks of the zeta method

### ISSUE THREAD

**Issue by willettk** [willettk/gzhubble#46]
Old suggestions from @chrislintott (Jul 2015 telecon), noted here for completeness:
- Plot zeta as a function of color to examine what effect that has on the boosting
- Look at the galaxies getting significantly boosted. What did the CANDELS team (GOODS) in Jeyhan's catalog say about those? Are they really marginal disks?
- What is the evolution of the cutoff p_features-mu point as a function of redshift? Is it a linear fit? If so, could we extrapolate it to CANDELS?

**Comment by willettk** [comment]
Regarding point 2: we matched GZH against Kartaltepe+15, Table 3. We looked at galaxies in the correctable sample with p_features,raw < 0.2 and p_features,best > 0.5 (so galaxies getting significantly boosted from smooth to disks). K15 only have eight such galaxies in their sample. Of those, they classify:
- 5 as spheroids
- 2 disks
-  1 irregular/disk

Visual inspection of the ACS images shows almost all at very low surface brightness, so it's difficult to tell if features are present. At least one of the K15 spheroids looks to have an extended component that the CANDELS classifiers missed. 

Caveats: sample size is only 8 galaxies; entirely different wavelengths and image conditions; difficulty in matching their vote fractions to GZH (see Brooke's GZC paper).

**Comment by vrooje** [comment]
Did any of the K15 galaxies get marked in that catalog as having a morphological K-correction (one of the bands having a significantly different morphology than H... usually the ACS band)?

**Comment by willettk** [comment]
Do you know what that column would be named in K15, by any chance?

**Comment by vrooje** [comment]
It's 3 columns: f_?diff where ? is V, z, or J. From looking at the catalogs most of the things with really high values of one or more of those appear to be dropouts.

**Comment by willettk** [comment]
Don't see that in this catalog - there's f_Flag?_ with V, z, and J ...

**Comment by vrooje** [comment]
Hmm, maybe it changed names between the team version and the public version? It's columns 23-25 in the catalog I have...
