### ISSUE TITLE
Text in Section 

### ISSUE THREAD

**Issue by Mel23** [willettk/gzhubble#47]
- [x] Task 1
  Calculate average % of correctable ferengi galaxies for all tasks to justify why we are unable to offer debiased values for these 
- [x] Task 2 
  Evaluate corrected values, show images of corrected galaxies 
  3 categories: spirals w/ no correction, big correction for 3 types (correctable, lower-limit, NEI)

**Comment by willettk** [comment]
Closed with b12c67ff5d1d9370516bccdd2db90913adde3ab6.
