### ISSUE TITLE
Detailed description of the table structure

### ISSUE THREAD

**Issue by willettk** [willettk/gzhubble#53]
This should likely be in the repo as an accompaniment to the paper, but won't be in the actual manuscript.

**Comment by Mel23** [comment]
Files are located on the column_descriptions branch in the gzhubble/column_descriptions folder. 3 items to resolve before closing this issue:

1) Should there be a description file for _every_ data table, even if they are identical? (Ie the columns in all the votes catalogs are identical except fake_agn.) It depends on if we want an easy link with matching filenames accompanied with each table. 

2) I don't know the source of the metadata for goods_full - I believe you compiled them @willettk ?

3) The metadata for the hubble galaxies (except goods_full) are mostly from Griffith et al. 2012, but the paper does not specify units for many of the Galfit and SExtractor measurements, nor do the readme files. 

These files can be edited pretty easily in the browser too, if anyone wants to help tackle finishing these up.

**Comment by willettk** [comment]
1. Yes, I think so. We can just copy and paste the file names, but I don't see any reason to not make it super clear and have one per table.
2. Metadata for GOODS 5-epoch was from most of the same sources you used for the remaining Legacy samples; I combined 3DHST, MUSYC, and the ACS-GC while matching on position in the larger mosaics. 
3. If you can post a list of the fields you don't have measurements for, the science team can probably help determine what they are. Or email Roger directly - he's a coauthor on the paper (although I haven't heard back from him on the draft).

**Comment by Mel23** [comment]
1. Great
2. I might need a little more assistance; the following columns are ones that don't appear to be described in any of the catalogs:

absolute_size  
counters_feature  
counters_smooth  
counters_star  
flux_radius1_I

The rest are self-explanatory, I think. 
1. I e-mailed Roger, hopefully he can clear that up.

**Comment by willettk** [comment]
counters_feature, counters_smooth, and counters_star are just copies of t00_smooth_or_features_a00_smooth_count, *_features_or_disk_count, and *_star_or_artifact_count. They somehow got copied over from the subjects category; those should be removed. 

absolute_size is the I-band Kron radius, converted into a projected physical size in kpc using the redshift and WMAP9 cosmology. 

flux_radius1_I should be taken from MUSYC, I think - it's a radius in I-band, with the number 1 referring to the flexible scaled size of the aperture in pixels. I'd ask Carie about that; if she doesn't know, then drop it as a metadata column.

**Comment by willettk** [comment]
Closed with #142.
