### ISSUE TITLE
Consistent use of p_features vs f_features

### ISSUE THREAD

**Issue by willettk** [willettk/gzhubble#66]

**Comment by vrooje** [comment]
I'm terrible at this myself but in print I use f_\* so that people don't assume we're talking about probabilities... or at least it's up to them to make that active choice.

**Comment by willettk** [comment]
Let's settle on `f_`, at least for the GZH paper. Will need to redo Figures 9, 10, 12, and all the Appendices.

**Comment by willettk** [comment]
I think I need help from @Mel23 for the final couple changes. Can you just change `p_features` -> `f_features` for Figure 9 and the ones in the Appendix? I don't see where those are made in the existing notebooks.

**Comment by willettk** [comment]
Closed with #67.
