### ISSUE TITLE
Finalize affiliations and author list

### ISSUE THREAD

**Issue by willettk** [willettk/gzhubble#69]
- [x] Affiliations
- [x] Author order
- [x] Grant acknowledgments
- [x] Survey or facilities

**Comment by karenlmasters** [comment]
Need to acknowledges Tom's PhD funding from STFC. "TM acknowledges funding from the Science and Tech- nology Facilities Council ST/J500665/1."

**Comment by karenlmasters** [comment]
Should Bill be on this?

**Comment by willettk** [comment]
He's welcome to be, although I wasn't sure of his participation level on the project so far. Haven't gotten any acknowledgment or comments from him yet.
