### ISSUE TITLE
IPython notebook version

### ISSUE THREAD

**Issue by bamford** [willettk/gzhubble#7]
When I open zeta.ipynb it warns me that the current version is v3, but if I save it will be in v4.   Just FYI!

**Comment by willettk** [comment]
According to http://ipython.org/install.html, 4.0 is the dev version right now and 3.1 is the "stable" one, as of Apr 2015. Is there a compelling reason to update? I worry that the 4.0 version appears to not be backwards-compatible ... (https://github.com/QuantEcon/QuantEcon.site/issues/19)

**Comment by bamford** [comment]
I've got a recently updated version of Anaconda, which includes IPython-3.1, but the ipython notebook saves in v4 notebooks.  I don't think the notebook versions track the IPython versions.

The incompatibility is definitely annoying!  I won't issue any pull requests that would overwrite your notebooks.
