### ISSUE TITLE
Distinguish calibration and bias.

### ISSUE THREAD

**Issue by chrislintott** [willettk/gzhubble#71]
I think it's really important to distinguish the following things:
1. Calibration or consensus - combining classification to produce a consensus (e.g. Willett et al for GZ2)
2. Bias - the tendency of faint, distant or small galaxies to appear featureless

If we distinguish them, then it's clearer that 1 is a crowdsourcing problem and 2 is a problem affecting all classifications to some degree. I'm thinking really about the introduction, but some consistent nomenclature would help throughout.

**Comment by vrooje** [comment]
Agreed it's definitely worth stating explicitly that bias is a problem affecting automated classifications too, and one that often goes uncorrected...

**Comment by karenlmasters** [comment]
I would really like us to use the term "redshift bias" rather than "morphological bias" so that we are making sure to point out this is not about the classifiers, but a feature of the actual image of the galaxy.

**Comment by willettk** [comment]
Good reminders. I've tried to use consistent phrasing ("redshift bias", not "morphological bias") and emphasized at the beginning of the debiasing section that this is not unique to visual classifications or crowdsourcing.
