### ISSUE TITLE
Distinguish different samples

### ISSUE THREAD

**Issue by chrislintott** [willettk/gzhubble#73]
Section 2 starts off well - I like the descriptions of the surveys. But by the time we're into Sloan, and then into 5-epoch GOODS sets and then COSMOS pseduocolour the reader will likely have lost track of which dataset is which. I suggest that we make section 2.2 a list of datasets with shorthand names for each whcih can then be used throughout the paper. (The content in 2.3 could go here too so as to keep the descriptions of image creation next to each dataset). 

If you agree, feel free to assign to me.

**Comment by vrooje** [comment]
I think this should be included in #120 but I haven't actually checked to see that my labels there are what's used throughout the paper, nor whether the usage is consistent in the paper.

**Comment by willettk** [comment]
Closed for the moment with #121 - will merit a final re-read and a note for anyone adding text to try and use the new labels.
