### ISSUE TITLE
Find a permalink to the current GZ version

### ISSUE THREAD

**Issue by chrislintott** [willettk/gzhubble#74]
Which is referred to in a footnote.

**Comment by chrislintott** [comment]
Feel free to assign to Adam.

**Comment by willettk** [comment]
Is this with an eye toward GZ moving to Panoptes in the future?

**Comment by chrislintott** [comment]
Just at some point it will change, and you want a link that refers as long as possible to the thing you're referring to.

**Comment by willettk** [comment]
Always true. My dream for that would be a permalink for each of the various datasets that we've put into GZ4 over the past couple of years, eg:

```
ukidss.galaxyzoo.org
candels.galaxyzoo.org
illustris.galaxyzoo.org
...
```

I've no good concept for how much work that'll be, though.

**Comment by chrislintott** [comment]
Talk to Adam...

**Comment by willettk** [comment]
True. Should be relevant for @vrooje's paper as well.

**Comment by willettk** [comment]
@astopy - The GZ team is submitting a couple of papers soon referencing versions of the current Ouroboros the site. We'd like to include a permalink (or as close as possible), similar to zoo2.galaxyzoo.org or zoo3.galaxyzoo.org, and not link to future versions of the main site. In an ideal situation, we might have permalinks for different datasets and a few dozen subjects active.

Could you comment on the technical feasibility of that, and any guess as to timescale/how much work it would be?

**Comment by vrooje** [comment]
The GZC paper links to zoo4.galaxyzoo.org, which appears to work...

**Comment by adammcmaster** [comment]
zoo4.galaxyzoo.org is actually a completely separate copy of the site which doesn’t seem to have been deployed since July 10, 2014. You can probably just use that URL, but we’ll want to figure out how to keep it updated whenever the main site is deployed. We can probably just modify the deploy script to upload everything to both places.

**Comment by willettk** [comment]
Thanks. That should be just fine for the purposes of this paper. In that case, there will be a strong case for keeping that URL active (with some version of the site) as long as possible, even when moving on to Panoptes some day.
