### ISSUE TITLE
Increase size of Figure 9

### ISSUE THREAD

**Issue by chrislintott** [willettk/gzhubble#75]
(a) and particularly (c) are too small to be usable.

**Comment by Mel23** [comment]
I could actually use some feedback on this. Our assumption was that showing every single bin in that plot might be a waste of space, even though we absolutely have to show some visual. The compromise was to show the full plot in less detail as an overview (ie subplots [a] and [c]) but to zoom in on one bin so the reader can get a close-up idea of the individual trends without the clutter ([b] and [d]). If we think it would be best to show the full figure blown-up to fit a full page, then the zoom-ins [b] and [d] would probably not be necessary. 

As Kyle and myself have stared at this plot for months now, suggestions from those viewing it fresh would be most appreciated.

**Comment by willettk** [comment]
I think one aspect that would help would be reducing the amount of white space between the subplots; if the plots and labels are bigger, that'll help with legibility. You may be able to massage the various positions in the `subfigure` package; if not, then put it together in one big figure in Python (or some other image editing software) and put it in the draft as a single figure. 

@chrislintott, is that what you meant? It'd be helpful for you say whether you think we need both pairs of images, or if just one of the two rows (`a/b` or `c/d`) is sufficient.

**Comment by vrooje** [comment]
I just think this is too much on the same page. Recommend (b) and (d) be the only panels in Figure 9, and (a) and (c) each be their own figure on a full page.

**Comment by vrooje** [comment]
(Such that the purpose of Figure 9 is to explain in detail what's to come in Figures 10 and 11)

**Comment by Mel23** [comment]
Thanks for that feedback Brooke. I feel that route makes sense but I'm worried it could feel like overkill, having that many large figured displaying ~ the same information. Tagging @karenlmasters and @chrislintott for their thoughts.

**Comment by rjsmethurst** [comment]
Also a note to say that you refer to "f_features" throughout the text - yet the axes labels in Figure 9 are "p_features"

And why does it say "redshift" at the top of each of panels (a) and (c) - isn't it the f_features that's changing along the axes? Not redshift... it's slightly confusing!

**Comment by karenlmasters** [comment]
What about an Appendix with (a) and (c) in full, and an excerpt in the main text to explain what's in the figure. You could also split up Figure A5 in the sample way - but now all in the Appendix...

**Comment by karenlmasters** [comment]
I do think (a very small number of) people will want to see all the fits, so we should include it at least in an Appendix, but perhaps not needed in the main body of the text?

**Comment by karenlmasters** [comment]
(Not about this issue - but how do I search where I'm tagged? I get so many github notifications from this repository, I can't find the important ones... like this one...).

**Comment by Mel23** [comment]
I was also thinking of having the full versions in the appendix, but having them in the main text does help to show very obviously what sim_z / mu ranges we're talking. Hard to decide what's best! Hoping we'll end up with some majority consensus here if enough people weigh in. 

Regarding how to search for where one is tagged, I'm not sure! That'd be a good thing to know though..I'll see if I can figure that out

**Comment by Mel23** [comment]
@rjsmethurst  - I think you were just commenting on the old version; the new version labels are f's not p's!

Regarding the labels - I do agree it's confusing, but we did do our best to make it the least so! The 'redshift' label at the top is indicating that z_sim increases in each bin, while _within_ each bin, f_features increases to the right. In other words: for the full figure, the bottom and left labels are indicating the x-y values of _each_ bin, and the top and right labels are indicating the z/mu range of each bin. If you have any thoughts for how to improve that labeling let us know; so far it's the best we've come up with.

**Comment by willettk** [comment]
@karenlmasters - here's how to find issues that you're tagged in (got there by clicking on the "Filters" button on the top left of the Issues page). 

https://github.com/willettk/gzhubble/issues?q=is%3Aopen+mentions%3Akarenlmasters

**Comment by karenlmasters** [comment]
Thought about this a bit more overnight, and I think I agree with @Mel23 that the full figure does need to be in the main text to show the redshift, mu ranges. They must be bigger though - they're basically useless at this size - so I think this should be split into 3 figures. Also the one in the Appendix. Let's let the ref/editor figure out how to format things and/or see what they think about the need for these.

**Comment by willettk** [comment]
Thanks for the excellent discussion on this. I don't think there's a strong overall consensus; @Mel23 and I have a compromise suggestion that I hope increases clarity. 
- Make Figure 9a) full-size and standalone
- Make Figure 9d) full-size and standalone

We can then see the overall trends as a function of mu and SB, and the more complicated version will focus on a single box.
