### ISSUE TITLE
Consider adding flags

### ISSUE THREAD

**Issue by chrislintott** [willettk/gzhubble#76]
I think we should consider adding flags at least for featured/smooth in table 5 - they've been useful in prior data releases.

**Comment by Mel23** [comment]
I agree these are useful; however slightly more complicated than previous releases, as the FERENGI analysis showed that for the "NEI" sample, it is not possible to discern whether a low f_features value is indicative of a true elliptical vs a featured galaxy whose features have been washed out. 

For those reasons I propose the following method of flagging:
- Flag "featured" if f_features > 0.23 for _any_ galaxy (based on Table 12)

-Flag "smooth" if f_features <  0.23, **only for non-NEI galaxies**. For NEI galaxies, we do not know whether they are naturally smooth or have washed out features. 

I'm interested in feedback on this, if this method seems reasonable I'll implement it.

**Comment by willettk** [comment]
Closed with #119.
