### ISSUE TITLE
Neglect dust lanes/lenses from f_odd when comparing to other galaxies

### ISSUE THREAD

**Issue by chrislintott** [willettk/gzhubble#77]
In general I'm in favour of the approach of making comparisons with other classifications in broad categories, and I think sec. 7.2 lays that out well. But galaxies can end up with high f_odd for having dust lanes, or being host to lenses. In these cases, I think we'd still consider them in the other categories, and so I suggest dropping these from the definition of f_odd used here. 

It won't matter for many galaxies, but will for some.

**Comment by willettk** [comment]
OK. It ended up affecting very few galaxies: 
- AEGIS: 23 galaxies (0.3%) with lenses or dust lanes removed
- GEMS: 19 galaxies (0.2%) with lenses or dust lanes removed
- GOODS: 18 galaxies (0.7%) with lenses or dust lanes removed
- COSMOS Cassata: 198 galaxies (0.3%) with lenses or dust lanes removed
- COSMOS Tasca: 199 galaxies (0.3%) with lenses or dust lanes removed
- COSMOS Scarlata: 204 galaxies (0.3%) with lenses or dust lanes removed

No change in the overall trends of Figure 12, but I've noted it in the text.
