### ISSUE TITLE
Improve discussion of figure 12

### ISSUE THREAD

**Issue by chrislintott** [willettk/gzhubble#78]
I don't think we're going to be able to say that our comparison with other classifications is 'interesting' and then show in the figure that with a few exceptions (Bundy, maybe Scarlata) f_features doesn't correlate with what other people call spirals.

We either need to come out and say that our classifications seem right or not. What do, for example, galaxies with Lotz or Boris have as spiral with low f_features look like?

This needs quite a lot of thought - we should discuss on this week's telecon.

**Comment by willettk** [comment]
Suggestions from telecon on 13 May 2016
- [x] Split by technique (expert vs Sersic vs machine learning)
- [x] Make a volume and/or luminosity-limited split
- [x] Check with @claudiascarlata on appropriate limits for COSMOS
- [x] Remove f_dust, f_lens from f_odd (#77)

**Comment by willettk** [comment]
Closed with #147.
