### ISSUE TITLE
Is it worth flagging those galaxies with contradicting spec-z?

### ISSUE THREAD

**Issue by chrislintott** [willettk/gzhubble#79]
As per sec 2.5, it's less than 2% of the sample but they might be distinctly odd in some figures that people will make, if their distances are very wrong.

**Comment by willettk** [comment]
It hadn't struck me as urgent, but it's something I think can be done. Will ask @Mel23 if she can add as a column, since she worked on assembling the redshifts initially.

**Comment by Mel23** [comment]
@willettk - can you clarify slightly? Do you mean add a flag column to the metadata table?

**Comment by willettk** [comment]
Yep.

**Comment by Mel23** [comment]
Closed with #105
