### ISSUE TITLE
Can I re-write abstract? 

### ISSUE THREAD

**Issue by karenlmasters** [willettk/gzhubble#83]
My suggestion (although Q - is it really the largest... I think it is): 

"We present the data release paper for the Galaxy Zoo: Hubble (GZH) project. This is the third phase in the Galaxy Zoo effort to measure reliable morphologies of galaxies by using crowd-sourced visual classifications. The color-composite images used in GZH are selected from various Hubble Space Telescope Legacy programs using the Advanced Camera for Surveys (AEGIS, COSMOS, GEMS, GOODS-N, and GOODS-S), with filters which probe the rest-frame optical emission from galaxies out to z ~ 1. The galaxies selected for GZH classifications go down to magnitude limits of mI814W < 23.5 and have a median redshift of ⟨z⟩ = 0.9 ± 0.6, with a tail extending out to z ≃ 4. The GZH morphological data includes measurements of both bulge- and disk-dominated galaxies, details on spiral disk structure that relate to the Hubble type, bar identification, and numerous measurements of clump identification and geometry. This paper also describes a method for calibrating morphological redshift bias by using artificially-redshifted galaxy images as a baseline. The GZH catalog includes both the raw and calibrated morphological vote fractions for 150,771 galaxies, providing the largest data set to date suitable for large-scale studies of galaxy evolution out to z~1."

**Comment by bamford** [comment]
I suggest "and numerous measurements of" --> "as well as", since with don't measure "identification".

**Comment by willettk** [comment]
Both @bamford and @vrooje already made some small changes to the abstract in the current draft, @karenlmasters. Can you take another quick look and see if you want to make more changes (totally welcome)? You can either submit a pull request or post the text here.
