### ISSUE TITLE
Comments on Intro

### ISSUE THREAD

**Issue by karenlmasters** [willettk/gzhubble#84]
- [x] ellipticals are not the only early-types:  "bulge-dominated, virialized systems resembling ellipticals (early-types)"  -> "bulge-dominated systems with no/little spiral structure (early-types)" (early-type is sometimes even Sa/S0/E I recently realised - e.g. in Strateva et al. 2001 that's the definition - they even have red spirals.....). 
- [x] disk-dominated, rotationally-supported disks (late-types) -> disk-dominated, rotationally-supported galaxies (late-types)
- [x] Can we find additional/alternative reference to Conselice (2014) on the importance of morphology for galaxy evolution? Ron Buta maybe? 
- [x] Like to mention Steinmetz & Navarro 2002 who claim morphologies are all caused by hierarchical merging ...
- [x]  Think Bell et al. 2012 needs citing in here on: "WHAT TURNS GALAXIES OFF? THE DIFFERENT MORPHOLOGIES OF STAR-FORMING AND QUIESCENT GALAXIES SINCE Z ∼ 2 FROM CANDELS"
- [x]  is r propto (1+z)^-1 different from angular diameter distance? Does it need citing...? 
- [ ] Add footnote pointing to zooniverse.org/publications when mention all GZ results? 
- [x] "This paper presents the results from the Galaxy Zoo Hubble (GZH) project." -> "This paper presents the classifications collected during the Galaxy Zoo Hubble (GZH) project."

**Comment by bamford** [comment]
Would be nice to cite a more general and inclusive review than C14.
- [x] Is r propto (1+z)^-1 from Mao, Mo & White (http://adsabs.harvard.edu/abs/1998MNRAS.297L..71M)

This checklist approach looks like better than trying to edit directly (https://github.com/willettk/gzhubble/pull/88).  What do you prefer @willettk?

**Comment by karenlmasters** [comment]
(sorry about the title from Bell et al. 2012 which looks very shouty now I re-read it - was just copy paste!). 

I'd like to echo @bamford question - is this better than direct edit? I thought perhaps direct edit might get confusing as this point.... @willettk

**Comment by willettk** [comment]
@karenlmasters - if you'd like any discussion or it's a non-obvious change, issues are probably better so that anyone interested can participate. For many of the points above (especially if it's just things like wording or adding references), I'm happy for you to just submit a pull request.

**Comment by willettk** [comment]
@karenlmasters - the only point left above was for the publications page. I'm not sure why I feel a little reluctant to mention it - the paper citations do feel more permanent. If you think it's a need, though, I can add it back in.

**Comment by karenlmasters** [comment]
I like it because it shows how many publications GZ has without needing to cite all of them (which at this point seems like over-kill). But if people feel strongly we shouldn't refer to websites I can live without it.

**Comment by willettk** [comment]
Not super strongly, but there's the lack of permanence and attribution (although it does mean people may complain about the specific papers I've chosen). I think I'm going to leave it for now.
