### ISSUE TITLE
Do we need Fig 2

### ISSUE THREAD

**Issue by karenlmasters** [willettk/gzhubble#86]
I think it's a waste of space if the web has a perma link... but could be persuaded.

**Comment by chrislintott** [comment]
We do. Journals are ~for ever and GZ is probably not.

**Comment by willettk** [comment]
Agreed - it's surprising how difficult it's been for me to find screenshots of the GZ1 interface at this point in time and many of the other projects. Even with the best of intentions on our part, there are lots of software failure modes that might leave a permalink inaccessible.

**Comment by karenlmasters** [comment]
OK fine I'm convinced.
