### ISSUE TITLE
Figure 5 - made by Nuffield student? 

### ISSUE THREAD

**Issue by karenlmasters** [willettk/gzhubble#87]
Is Figure 5 the version from Tom's thesis made by our 2015 Nuffield Student. If so his name was Joe Hind, and maybe acknowledgement? If not never mind...

**Comment by willettk** [comment]
I thought @Mel23 made that figure, but she should confirm that either way.

**Comment by Mel23** [comment]
Not me! This figure has been in the writeup since the repo was created (or since before I was added as a collaborator, anyway). Who would be best at tracking down the source? @karenlmasters ?

**Comment by willettk** [comment]
It looks like @karenlmasters committed it back at the Taiwan workshop (7865fbe6fcf49312a36562f1fc85e0655ce35d74), so she should be able to speak to that. Tom does have a similar figure in an old version of his thesis chapter that I have, but it's of different galaxies:

![screen shot 2016-05-16 at 2 45 48 pm](https://cloud.githubusercontent.com/assets/2285931/15301744/eee5d59c-1b74-11e6-899f-0397e7335e2f.png)

If you can confirm whoever made it, Karen, I'll add appropriate credit to the acknowledgments.

**Comment by vrooje** [comment]
I thought Edmond made those? No?

I have a vague recollection of trying to edit them to enlarge some of the
labels and being unsuccessful despite getting the images directly from
Edmond.

**Comment by willettk** [comment]
Also a possibility - thanks, Brooke. I'll ask him directly.

**Comment by willettk** [comment]
@ec2250 (Edmond) confirms that he made the figure originally, so we're good with attribution.

**Comment by karenlmasters** [comment]
OK sorry for the confusion. I was remembering the figure in Tom's thesis.
