### ISSUE TITLE
Steven's comments on section 2

### ISSUE THREAD

**Issue by bamford** [willettk/gzhubble#89]
- [x] Sec 2.1, before bulleted list: "The properties of the individual surveys are as follows."
- [x] There is a bit of inconsistency between table 1, figure 1 and the text of 2.3 regarding the GOODS bands, e.g. fig1 shows F850LP for GOODS-S shallow, but not deep; text says F850LP used for red band in GOODS deep; table 1 doesn't include F814W in list for GOODS.
- [x] Table 1 could specify the appropriate bands for each of the GOODS samples individually.
- [ ] Table 1 could specify the filter used for blue, green and red channel, e.g. "V606W, (V606W/2 + I814W/2), I814W"

More to come...

**Comment by bamford** [comment]
- [ ] If included in data release, need to mention faded and recoloured COSMOS images.

From the ancient but venerable http://plan.zooniverse.org/projects/galaxyzoosci/wiki/Galaxy_Zoo_Hubble:

> ### cosmos_initial and cosmos_test_initial
> 
> In late December 2010 a further 86314 images were added from the COSMOS survey. These comprise 78460 'normal' images and two additional sets of test mages (each of 3927 images, 5% of the COSMOS sample) which have been altered for the purpose of evaluating the impact of colour on the classifications.
> 
> The first test set are 'faded' to almost, but not quite, grayscale by reducing their saturation. My reason for not simply converting them to true grayscale is because then it is quite obvious what has been done to the image, and the classifier will potentially be alerted to the fact that they are being tested. By fading, and retaining a little colour information the image is much harder to distinguish from a 'normal' image, and so users behaviour should be less affected. The second set have had the blue and red colour channels swapped, which very effectively turns blue galaxies red and vice versa. This enables an alternative and arguably stronger test of any colour biases in the classifications. There is an extremely draft version of an internal document (GZ image creation), or possibly part of the eventual GZ:Hubble overview paper, with a figure (on page three) which illustrates these transformations. To distinguish the test images from the normal images I appended a single digit on the end of their OBJNO id ('1'=faded or '2'=recoloured).

**Comment by willettk** [comment]
#111 addresses Figure 1, but the text and table should be fixed now (24de2a3c19ba9f08f446ac194b523e8b03251ca4). 

I tried listing the filters by RGB channel, but thought it was a confusing method of looking at the table. I can be talked out of that if others feel more strongly, though. 

The point on faded & recolored images should still stay active, but I'll defer that to the larger Section 2 reorganization.

**Comment by bamford** [comment]
Yes, I realise (now) that I completely forgot to mention the faded and recoloured images! I'll wait until @vrooje and @willettk are done with sec. 2 and then can add something in if still required.

**Comment by vrooje** [comment]
👍  I'd been holding off on rearranging S2 because lots of people were still editing, but I'll get going on that now.

**Comment by willettk** [comment]
A lot of this has been addressed in #120. @bamford, anything more you want to add?

**Comment by bamford** [comment]
Section 2 is now really clear.

I just have a couple of minor points:
- [x] Sec 2.3.1: "Combining these parameters generated _15_ images with different simulated AGN for each host, in addition to the original galaxy image."
  ... but 6 \* 3 = 18, so why 15?
- [ ] Sec 2.3.2: "we include a sample of 288 galaxies with ~~at~~ redshifts"

**Comment by willettk** [comment]
Good catch, Steven - there is no `l_rat = 2.0`, so only 5 levels at 15 total.
