### ISSUE TITLE
Some filters are incorrect in Figure 1

### ISSUE THREAD

**Issue by vrooje** [willettk/gzhubble#91]
GEMS, GOODS-S (top right panel): F850LP isn't shaped like that.
http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=HST/ACS_WFC.F850LP_81&&mode=browse&gname=HST&gname2=ACS_WFC#filter

Deep GOODS-N, -S (lower center): figure has F814W instead of F850LP.

Also, verify that shallow GOODS-N (top left) uses F775W instead of F850LP?

**Comment by bamford** [comment]
Maybe the plot is showing the filter transmission curves, rather than the whole system efficiency (which is the more important quantity)?  I think in SDSS (at least) the z-band red cutoff is due to CCD efficiency, rather than the filter itself (hence why it is so gradual).

**Comment by willettk** [comment]
These should be the total throughput of the system -- ratio (fraction, really) of photons vs. photo-detected electrons on the CCD. The data I used for this are from the horse's mouth, I would have thought: http://www.stsci.edu/hst/acs/analysis/throughputs/tables

and plotted with https://github.com/willettk/gzhubble/blob/master/python/filter_curves.py

**Comment by willettk** [comment]
I take it back - I got the throughput from http://www.stsci.edu/hst/observatory/crds/SIfileInfo/pysynphottables/current_acs_throughput_html

**Comment by bamford** [comment]
Yeah, on the linked page you can see the plot of the throughput dropping off with the ccd quantum efficiency. The synphot curves must separate out the two effects.

On 15 May 2016, at 18:53, Kyle Willett notifications@github.com wrote:

These should be the total throughput of the system -- ratio (fraction, really) of photons vs. photo-detected electrons on the CCD. The data I used for this are from the horse's mouth, I would have thought: http://www.stsci.edu/hst/acs/analysis/throughputs/tables

and plotted with https://github.com/willettk/gzhubble/blob/master/python/filter_curves.py

**Comment by willettk** [comment]
Re: @vrooje's original comments:
- is the plot of throughput acceptable? I can add a footnote for the sources of the curves, if we need.
- changing plot for deep GOODS-N and -S. good catch, thank you. 
- shallow GOODS-N for our images does use F775W. Stated in Griffith+12, and I've looked at the raw FITS i-band images as well.

**Comment by vrooje** [comment]
I think we should plot the ones on the original page - that is, if I download WFC/F850LP I get this:

![screen shot 2016-05-16 at 4 36 42 pm](https://cloud.githubusercontent.com/assets/2357126/15307086/b1f3c706-1b84-11e6-9ecb-88a207f019b6.jpg)

which looks right to me.

**Comment by bamford** [comment]
I agree, current ones will probably confuse.

On 17 May 2016, at 00:39, Brooke Simmons notifications@github.com wrote:

I think we should plot the ones on the original page - that is, if I download WFC/F850LP I get this:

which looks right to me.

**Comment by willettk** [comment]
Closed with #111.
