### ISSUE TITLE
Remove justification for using 2-epoch GOODS data

### ISSUE THREAD

**Issue by vrooje** [willettk/gzhubble#98]
Section 2.3, the paragraph after equation 1, starts with:

> The majority of the data in Legacy surveys described in Section 2.1 had images in only one or two filters available when the GZH project was first launched.

The "majority" is later described to include the 2-epoch GOODS-N and GOODS-S data. But that's not the case. The v1 GOODS data release in 2003 included stacked images of all 4 bands, and followed the v0.5 release that included individual epochs in _BVIz_ (which would have been trivial to stack into 2-epoch images). Version 2 was released in 2008, still in plenty of time for GZH. 

I wasn't on the GZ team at the time the original images were created, so I don't know why only the 2-epoch data was initially used with 2 filters, but I'm guessing it was because this provided the most apples-to-apples comparison with the other surveys? Anyway, it doesn't matter what the thinking was at the time. We should just say that both 2-filter-2-epoch and 4-filter-full-depth images were used, and in the next sentence state that the shallower 2-filter image classifications provide easier comparison with the wider, shallower surveys, while the full-depth and full-color classifications make full use of the data in the pencil-beam survey.

**Comment by bamford** [comment]
We simply used the images from Roger Griffith's dataset, but I guess that the use of two bands was to be consistent with the other surveys, as you suggest.  In [Griffith et al. (2012)](http://adsabs.harvard.edu/abs/2012ApJS..200....9G) it acknowledges that four band data was available, but simply says:

> We restrict our analysis to the F606W and F775W imaging in GOODS-N and the F606W and F850LP imaging in GOODS-S. For GOODS-S we analyzed the F850LP filter in order to combine directly with the GEMS F850LP imaging.

**Comment by bamford** [comment]
Found in an email from Roger:

> The reason with only using two colors is because the other HST surveys uses two colors, and sometimes the green image makes sources greener then they should be, I think the two bands are sufficient enough for our purposes of creating 'true' color images, take a look at the images I made an decide for your self.

**Comment by bamford** [comment]
Oops, no ignore that, it was something about the COSMOS image creation.
